import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import PageHeader from "@/components/PageHeader/PageHeader";
import PageFooter from "@/components/PageFooter/PageFooter";

const jost = Jost({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-jost",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${jost.variable}`}>
      <body>
        <PageHeader></PageHeader>
        {children}
        <PageFooter></PageFooter>
      </body>
    </html>
  );
}
